# GitHub Labels Configuration
# Use with: gh label sync --labels .github/labels.yml

# TYPE LABELS (Purple family)
- name: "type: feature"
  color: "7057ff"
  description: "New functionality"
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "type: enhancement"
  color: "a2eeef"
  description: "Improvement to existing feature"
- name: "type: refactor"
  color: "fbca04"
  description: "Code restructuring"
- name: "type: docs"
  color: "0075ca"
  description: "Documentation changes"
- name: "type: test"
  color: "1d76db"
  description: "Test additions or fixes"
- name: "type: security"
  color: "ee0701"
  description: "Security-related work"
- name: "type: performance"
  color: "ff9800"
  description: "Performance optimization"
- name: "type: devops"
  color: "0e8a16"
  description: "CI/CD and infrastructure"
- name: "type: dependency"
  color: "0366d6"
  description: "Dependency updates"

# YOUR SPECIFIC TYPES (Custom colors)
- name: "type: ai-generation"
  color: "8b5cf6"
  description: "AI/LLM integration work"
- name: "type: branding"
  color: "ec4899"
  description: "Brand Factory features"
- name: "type: web3"
  color: "f59e0b"
  description: "Smart contracts, x402, NFT"
- name: "type: design-system"
  color: "10b981"
  description: "Tokens, components, theming"
- name: "type: accessibility"
  color: "6366f1"
  description: "WCAG compliance work"
- name: "type: automation"
  color: "8b5cf6"
  description: "Scripts and workflows"

# PRIORITY LABELS (Red family)
- name: "priority: critical"
  color: "b60205"
  description: "Production down, security breach"
- name: "priority: high"
  color: "d93f0b"
  description: "Blocking work, major bugs"
- name: "priority: medium"
  color: "fbca04"
  description: "Normal priority"
- name: "priority: low"
  color: "0e8a16"
  description: "Nice to have"
- name: "priority: backlog"
  color: "c5def5"
  description: "Future consideration"

# FEATURE AREA LABELS (Blue family)
- name: "area: ui-generation"
  color: "1d76db"
  description: "Prompt-to-component system"
- name: "area: color-system"
  color: "5319e7"
  description: "Color palette generation"
- name: "area: brand-factory"
  color: "0052cc"
  description: "Branding questionnaire/generation"
- name: "area: design-tokens"
  color: "006b75"
  description: "CSS custom properties"
- name: "area: components"
  color: "1d76db"
  description: "React component library"
- name: "area: templates"
  color: "0e8a16"
  description: "Component templates"
- name: "area: api"
  color: "d4c5f9"
  description: "Backend API endpoints"
- name: "area: contracts"
  color: "f59e0b"
  description: "Smart contracts (Foundry)"
- name: "area: payments"
  color: "fbca04"
  description: "x402 integration"
- name: "area: nft-minting"
  color: "ff9800"
  description: "NFT reward system"
- name: "area: ci-cd"
  color: "0e8a16"
  description: "GitHub Actions workflows"
- name: "area: testing"
  color: "1d76db"
  description: "Test infrastructure"
- name: "area: docker"
  color: "0db7ed"
  description: "Containerization"
- name: "area: monitoring"
  color: "5319e7"
  description: "Observability, logging"

# STATUS LABELS (Yellow/Orange family)
- name: "status: blocked"
  color: "d93f0b"
  description: "Cannot proceed (dependency)"
- name: "status: in-progress"
  color: "fbca04"
  description: "Actively being worked on"
- name: "status: review"
  color: "ff9800"
  description: "Code review needed"
- name: "status: testing"
  color: "1d76db"
  description: "In QA/testing phase"
- name: "status: deployed"
  color: "0e8a16"
  description: "Live in production"
- name: "status: on-hold"
  color: "c5def5"
  description: "Paused/deferred"
- name: "status: needs-design"
  color: "ec4899"
  description: "Requires design review"
- name: "status: needs-research"
  color: "8b5cf6"
  description: "Research/exploration needed"
- name: "status: needs-feedback"
  color: "fbca04"
  description: "Awaiting stakeholder input"
- name: "status: needs-ai-test"
  color: "7057ff"
  description: "AI generation validation needed"

# EFFORT/COMPLEXITY LABELS (Green family)
- name: "effort: xs"
  color: "c2e0c6"
  description: "<2 hours"
- name: "effort: s"
  color: "7fdbca"
  description: "2-4 hours"
- name: "effort: m"
  color: "0e8a16"
  description: "1-2 days"
- name: "effort: l"
  color: "006b75"
  description: "3-5 days"
- name: "effort: xl"
  color: "0052cc"
  description: "1-2 weeks"
- name: "effort: xxl"
  color: "5319e7"
  description: "Multi-week epic"

# SKILL/EXPERTISE LABELS (Teal family)
- name: "skill: frontend"
  color: "06d6a0"
  description: "React/Next.js knowledge"
- name: "skill: backend"
  color: "118ab2"
  description: "Node.js/API development"
- name: "skill: solidity"
  color: "ffd60a"
  description: "Smart contract development"
- name: "skill: design"
  color: "ec4899"
  description: "UI/UX design"
- name: "skill: devops"
  color: "0e8a16"
  description: "Infrastructure/CI/CD"
- name: "skill: ai-prompt"
  color: "8b5cf6"
  description: "LLM prompt engineering"
- name: "skill: accessibility"
  color: "6366f1"
  description: "WCAG/a11y expertise"
- name: "skill: good-first-issue"
  color: "7057ff"
  description: "Good for new contributors"

# QUALITY LABELS (Pink family)
- name: "quality: needs-tests"
  color: "e99695"
  description: "Missing test coverage"
- name: "quality: needs-docs"
  color: "0075ca"
  description: "Documentation required"
- name: "quality: needs-a11y-audit"
  color: "6366f1"
  description: "Accessibility check needed"
- name: "quality: needs-perf-test"
  color: "ff9800"
  description: "Performance validation"
- name: "quality: regression-risk"
  color: "d93f0b"
  description: "High risk of breaking changes"

# AI-SPECIFIC LABELS (Purple family)
- name: "ai: prompt-engineering"
  color: "8b5cf6"
  description: "Prompt optimization"
- name: "ai: model-testing"
  color: "a78bfa"
  description: "LLM output validation"
- name: "ai: generation-quality"
  color: "c4b5fd"
  description: "AI output quality issues"
- name: "ai: token-optimization"
  color: "7c3aed"
  description: "Reduce token usage"

# WEB3-SPECIFIC LABELS (Orange family)
- name: "web3: contract-audit"
  color: "d93f0b"
  description: "Security audit needed"
- name: "web3: gas-optimization"
  color: "ff9800"
  description: "Reduce gas costs"
- name: "web3: testnet"
  color: "fbca04"
  description: "Testnet deployment"
- name: "web3: mainnet"
  color: "f59e0b"
  description: "Mainnet deployment"

# COMPLIANCE LABELS (Indigo family)
- name: "compliance: wcag-aa"
  color: "6366f1"
  description: "WCAG AA requirement"
- name: "compliance: wcag-aaa"
  color: "4f46e5"
  description: "WCAG AAA requirement"
- name: "compliance: gdpr"
  color: "5319e7"
  description: "GDPR compliance"
- name: "compliance: security"
  color: "b60205"
  description: "Security review needed"

# COMMUNITY LABELS (Various)
- name: "community: help-wanted"
  color: "008672"
  description: "External contributor welcome"
- name: "community: discussion"
  color: "d4c5f9"
  description: "Needs team discussion"
- name: "community: question"
  color: "d876e3"
  description: "Support question"
- name: "community: feedback"
  color: "fbca04"
  description: "User feedback item"

# WORKFLOW LABELS (Gray family)
- name: "workflow: skip-ci"
  color: "d4c5f9"
  description: "Skip CI/CD (docs only)"
- name: "workflow: needs-approval"
  color: "fbca04"
  description: "Manual approval required"
- name: "workflow: auto-merge"
  color: "0e8a16"
  description: "Auto-merge when passing"
- name: "workflow: breaking-change"
  color: "d93f0b"
  description: "Breaking API change"

# RELEASE/MILESTONE LABELS (Gold family)
- name: "release: mvp"
  color: "ffd700"
  description: "Minimum viable product"
- name: "release: v1.0"
  color: "ffb700"
  description: "Planned for v1.0"
- name: "release: beta"
  color: "ff9800"
  description: "Beta release"
- name: "milestone: public-launch"
  color: "7057ff"
  description: "Public launch milestone"
- name: "milestone: event-demo"
  color: "ec4899"
  description: "For MACHLABS event"
- name: "milestone: web3-integration"
  color: "f59e0b"
  description: "Web3 integration complete"
